version: '3'

services:
  prometheus:
    image: gilir/rpi-prometheus
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=false
    volumes:
      - prometheus_config:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - proxy-network

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  prometheus_config:
    external: true
